config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
    get 'recommendation', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
  resources :styles do
    get 'about', on: :collection
  end
  resources :ratings, only: [:index, :show, :new, :create]
  delete 'ratings', to: 'ratings#destroy'
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'styles', to: 'styles#index'
  # get 'styles/:id', to: 'styles#show', as: 'style'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to:'ratings#new'
  # post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'chat', to: 'messages#index'
  post 'messages', to: 'messages#create'
  get 'calculator', to: 'misc#calculator'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'breweries#index'

end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :beer_club

  validates_uniqueness_of :user_id, scope: :beer_club_id
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[show edit update destroy]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
    @beer_clubs = BeerClub.all.filter { |b| !b.members.include?(current_user) }
  end

  # GET /memberships/1/edit
  def edit
    @beer_clubs = BeerClub.all.filter { |b| !b.members.include?(current_user) }
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @beer_clubs = BeerClub.all.filter { |b| !b.members.include?(current_user) }

    respond_to do |format|
      if @membership.save
        format.html { redirect_to beer_club_path(@membership.beer_club), notice: "#{current_user.username} welcome to the club." }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    @beer_clubs = BeerClub.all.filter { |b| !b.members.include?(current_user) }

    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to membership_url(@membership), notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    club_name = @membership.beer_club.name
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: "Membership in #{club_name} ended." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def membership_params
    params.require(:membership).permit(:beer_club_id, :user_id)
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<% if @membership.new_record? && @beer_clubs.empty? %>
  <p>No clubs available... :/</p>
<% else %>
  <%= form_with(model: membership) do |form| %>
    <% if membership.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

        <ul>
          <% membership.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.select :user_id, options_for_select([[current_user.username, current_user.id]]) %>
    <%= form.select :beer_club_id, options_from_collection_for_select(@beer_clubs, :id, :name) %>
    <%= form.submit %>
  <% end %>


<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Beer club:</strong>
    <%= membership.beer_club_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= membership.user_id %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/show.html.erb
<%= render @membership %>

<div>
  <%= link_to("Edit this membership", edit_membership_path(@membership)) if current_user %>
  <%= " | " if current_user %>
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to("Destroy this membership", @membership, method: :delete) if current_user %>
</div>