config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
    get 'recommendation', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
  resources :styles do
    get 'about', on: :collection
  end
  resources :ratings, only: [:index, :show, :new, :create]
  delete 'ratings', to: 'ratings#destroy'
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'styles', to: 'styles#index'
  # get 'styles/:id', to: 'styles#show', as: 'style'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to:'ratings#new'
  # post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'chat', to: 'messages#index'
  post 'messages', to: 'messages#create'
  get 'calculator', to: 'misc#calculator'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'breweries#index'

end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage

  has_secure_password

  validates :username, uniqueness: true,
            length: { minimum: 3, maximum: 30 }

  validates :password, length: { minimum: 4 }, format: { with: /\A(?=.*[A-Z])(?=.*[0-9]).{4,}\z/,
                                                         message: "must be atleast 4 characters and include one number and one uppercase letter" }

  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships, dependent: :destroy
  has_many :beer_clubs, through: :memberships
  has_many :messages, dependent: :destroy

  scope :most_active, -> { all.sort_by { |u| -u.ratings.count }.take(3) }

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).limit(1).first.beer
  end

  def favorite_style
    return nil if ratings.empty?

    ratings
      .group_by { |r| r.beer.style }
      .transform_values { |value|
        sum = value.reduce(0.to_d) { |acc, cur| acc + cur.score }
        avg = value.empty? ? 0 : sum * 1.0 / value.count
        avg.to_f
      }.max_by { |_key, value| value }[0]
  end

  def favorite_brewery
    return nil if ratings.empty?

    ratings
      .group_by { |r| r.beer.brewery }
      .transform_values { |value|
        sum = value.reduce(0.to_d) { |acc, cur| acc + cur.score }
        avg = value.empty? ? 0 : sum * 1.0 / value.count
        avg.to_f
      }.max_by { |_key, value| value }[0]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :ensure_that_admin, only: %i[toggle_activity]
  before_action :ensure_that_signed_in, except: %i[new create]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && (@user == current_user) && @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
    end

    redirect_to users_path, notice: "User was successfully destroyed."
    # respond_to do |format|
    #   format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    #   format.json { head :no_content }
  end

  def toggle_activity
    user = User.find(params[:id])
    user.update_attribute :active, !user.active

    redirect_to users_path, notice: "User #{user.username} activity status changed to #{user.active}"
  end

  def recommendation
    ids = Beer.pluck(:id)
    random_beer = Beer.find(ids.sample)
    render partial: 'recommendation', locals: { beer: random_beer }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div>
      <%= form.label :username, style: "display: block" %>
      <%= form.text_field :username %>
    </div>
  <% end %>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_ratings.html.erb
<div data-controller="ratings" class="ratings mb-4">
  <%= turbo_frame_tag "ratings" do %>
    <% @user.ratings.each do |rating| %>
      <div class="rating">
        <% if @user == current_user %>
          <input type="checkbox" name="ratings[]" value="<%= rating.id %>"/>
        <% end %>
        <span>
        <%= link_to rating.to_s, rating, data: { turbo_frame: 'rating_details' } %>
        </span>
      </div>
    <% end %>
    <p><label>select all <input type="checkbox" id="select_all" data-action="ratings#selectAll"></label></p>
    <% if @user == current_user %>
      <button data-action="ratings#destroy">Delete selected</button>
    <% end %>
  <% end %>
</div>

app/views/users/_recommendation.html.erb
<%= turbo_frame_tag "beer_recommendation_tag" do %>
  <div>
    <h4>Recommendation based on your ratings</h4>

    <p><%= link_to beer.name, beer %> by <%= link_to beer.brewery.name, beer.brewery %></p>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Change password for user <%= @user.username %></h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <% if user.active or current_user.admin? %>
      <div>
        <p>
          <strong>Username:</strong>
          <%= user.username %>
          <% unless user.active %>
            <span class="badge bg-primary">disabled</span>
          <% end %>
        </p>
        <p>
          <%= link_to "Show this user", user %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>
<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div>
  <h2>Username:</h2>
  <p><%= @user.username %></p>
  <% if @user.ratings.empty? %>
    <p>Has not made any ratings yet!</p>
  <% else %>
    <p>Has made <%= pluralize(@user.ratings.count, 'rating') %>, average rating <%= round(@user.average_rating) %></p>
    <p>Favorite style is <%= @user.favorite_style.name %></p>
  <% end %>
</div>
<div>
  <% if current_user.admin? and (current_user != @user) %>
    <% if @user.active? %>
      <%= link_to "Disable account", toggle_activity_user_path(@user.id), data: { turbo_method: "post" }, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "Activate account", toggle_activity_user_path(@user.id), data: { turbo_method: "post" }, class: "btn btn-success" %>
    <% end %>
  <% end %>
</div>
<div>
  <p>
    <strong>member of</strong>
  </p>
  <ul>
    <% @user.beer_clubs.each do |beer_club| %>
      <li id="<%= dom_id beer_club %>">
        <%= link_to beer_club.name, beer_club %>
      </li>
    <% end %>
  </ul>
  <p>
</div>
<div>
  <h3>ratings</h3>
  <%= render partial: 'ratings' %>
  <%= turbo_frame_tag "rating_details" do %>
  <% end %>
</div>
<div>
  <%= turbo_frame_tag "beer_recommendation_tag", src: recommendation_user_path do %>
    calculating the recommendation...
  <% end %>
</div>

<div>
  <% if @user == current_user or current_user.admin? %>
    <%= link_to "Edit this user", edit_user_path(@user) %> |
  <% end %>
  <%= link_to "Back to users", users_path %>
  <% if @user == current_user %>
    <%= button_to "Destroy this user", @user, method: :delete, class: 'btn btn-danger' %>
  <% end %>
</div>