config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
    get 'recommendation', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
    get 'active', on: :collection
    get 'retired', on: :collection
  end
  resources :styles do
    get 'about', on: :collection
  end
  resources :ratings, only: [:index, :show, :new, :create]
  delete 'ratings', to: 'ratings#destroy'
  resource :session, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'styles', to: 'styles#index'
  # get 'styles/:id', to: 'styles#show', as: 'style'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to:'ratings#new'
  # post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'chat', to: 'messages#index'
  post 'messages', to: 'messages#create'
  get 'calculator', to: 'misc#calculator'
  # Defines the root path route ("/")
  # root "articles#index"
  root 'breweries#index'

end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage

  validates :name, presence: true
  validates :year, numericality: { greater_than_or_equal_to: 1040,
                                   less_than_or_equal_to: ->(_b) { Time.now.year },
                                   only_integer: true }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }
  scope :best_breweries, -> { all.sort_by(&:average_rating).reverse.take(3) }

  def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.count}"
  end

  def restart
    self.year = 2022
    puts "changed year to #{year}"
  end

  after_destroy_commit do
    count = active ? Brewery.active.count : Brewery.retired.count
    target_id = if active
                  "active_breweries_count"
                else
                  "retired_breweries_count"
                end

    broadcast_remove_to "breweries_index"
    broadcast_update_to "breweries_index", partial: "breweries/brewery_count", target: target_id, locals: { count: count }
  end

  after_create_commit do
    count = active ? Brewery.active.count : Brewery.retired.count
    target_id = if active
                  "active_brewery_rows"
                else
                  "retired_brewery_rows"
                end

    target_count_id = if active
                        "active_breweries_count"
                      else
                        "retired_breweries_count"
                      end

    broadcast_append_to "breweries_index", partial: "breweries/brewery_row", target: target_id
    broadcast_update_to "breweries_index", partial: "breweries/brewery_count", target: target_count_id, locals: { count: count }
  end

end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show, :active, :retired]
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /breweries or /breweries.json
  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    # @breweries = Brewery.all
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
    return unless turbo_frame_request?

    render partial: 'new'
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.turbo_stream {
          type = @brewery.active ? "active" : "retired"
          count = @brewery.active ? Brewery.active.count : Brewery.retired.count
          render turbo_stream:
                   [turbo_stream.append("#{type}_brewery_rows", partial: "brewery_row", locals: { brewery: @brewery }),
                    turbo_stream.update("#{type}_breweries_count", partial: "brewery_count", locals: { count: count })
                   ]
        }
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    brewery = @brewery
    @brewery.destroy
    type = brewery.active ? "active" : "retired"
    count = brewery.active ? Brewery.active.count : Brewery.retired.count

    respond_to do |format|
      format.turbo_stream {
        render turbo_stream:
                 [turbo_stream.remove(brewery),
                  turbo_stream.update("#{type}_breweries_count", partial: "brewery_count", locals: { count: count })
                 ]
      }
      format.html { redirect_to breweries_url, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, !brewery.active

    new_status = brewery.active? ? "active" : "retired"

    redirect_to brewery, notice: "brewery activity status changed to #{new_status}"
  end

  def active
    active_breweries = Brewery.active
    render partial: 'breweries', locals: { breweries: active_breweries, type: "active" }
  end

  def retired
    retired_breweries = Brewery.retired
    render partial: 'breweries', locals: { breweries: retired_breweries, type: "retired" }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_active_breweries.html.erb
<%= turbo_frame_tag "active_breweries_tag" do %>
  <h2>Active</h2>

  <p> Number of active breweries: <%= breweries.count %> </p>
  <% breweries.each do |brewery| %>
    <div>
      <p>
        <strong>Name: </strong> <%= link_to brewery.name, brewery, data: { turbo_frame: "_top" } %>
      </p>
      <p>
        <strong>Year: </strong> <%= brewery.year %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/breweries/_breweries.html.erb
<%= turbo_frame_tag "#{type}_breweries_tag" do %>
  <h2><%= type.capitalize %></h2>

  <p> Number of <%= type %> breweries:
    <span id=<%= "#{type}_breweries_count" %>>
      <%= render "brewery_count", count: breweries.count %></span>
  </p>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>Beers</th>
      <th>Rating</th>
    </tr>
    </thead>
    <tbody id="<%= type %>_brewery_rows">
    <% breweries.each do |brewery| %>
      <%= render "brewery_row", brewery: brewery %>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/breweries/_brewery.html.erb
<div id="<%= dom_id brewery %>">
  <h2><%= brewery.name %></h2>
  <p>
    <i>Established at <%= brewery.year %></i>
  </p>
  <p>
    Beers count: <%= brewery.beers.count %>
  </p>
  <p>
    <% brewery.beers.each do |beer| %>
      <%= link_to beer.name, beer %>
    <% end %>
  </p>
  <p>
    <% if brewery.ratings.empty? %>
      Brewery has not yet been rated!
    <% else %>
      Brewery has <%= pluralize(brewery.ratings.count, 'rating') %> with an average of <%= brewery.average_rating %>
    <% end %>
  </p>

</div>

app/views/breweries/_brewery_count.html.erb
<%= count %>

app/views/breweries/_brewery_list.html.erb
<div>
  <%= turbo_frame_tag "active_breweries_tag", src: active_breweries_path do %>

    <p>
      Loading active breweries...
    </p>
  <% end %>


  <%= turbo_frame_tag "retired_breweries_tag", src: retired_breweries_path do %>
    <p>
      Loading retired breweries...
    </p>

  <% end %>
</div>

app/views/breweries/_brewery_row.html.erb
<tr id="<%= dom_id(brewery) %>">
  <td><%= link_to brewery.name, brewery, data: { turbo_frame: "_top" } %></td>
  <td><%= brewery.year %></td>
  <td><%= brewery.beers.count %></td>
  <td><%= round(brewery.average_rating) %></td>
  <%# if current_user %>
    <td><%= link_to("X", brewery, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove brewery #{brewery.name} and all beers associated with it?" }) %></td>
  <%# end %>
</tr>

app/views/breweries/_form.html.erb
<div data-controller="breweries">
  <%= form_with(model: brewery, data: { action: "turbo:submit-end->breweries#reset" }) do |form| %>
    <% if brewery.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

        <ul>
          <% brewery.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, data: { "breweries-target": "name" } %>
    </div>

    <div>
      <%= form.label :year, style: "display: block" %>
      <%= form.number_field :year, data: { "breweries-target": "year" } %>
    </div>

    <div>
      <%= form.label :active %>
      <%= form.check_box :active, data: { "breweries-target": "active" } %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/breweries/_new.html.erb
<h1>New brewery</h1>

<%= turbo_frame_tag "new_brewery" do %>
  <%= render "form", brewery: @brewery %>
<% end %>

app/views/breweries/_retired_breweries.html.erb
<%= turbo_frame_tag "retired_breweries_tag" do %>
  <h2>Retired</h2>

  <p> Number of retired breweries: <%= breweries.count %> </p>
  <% breweries.each do |brewery| %>
    <p>
      <strong>Name: </strong> <%= link_to brewery.name, brewery, data: { turbo_frame: "_top" } %>
    </p>
    <p>
      <strong>Year: </strong> <%= brewery.year %>
    </p>
  <% end %>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<%= turbo_stream_from "breweries_index" %>
<%= render "brewery_list", active_breweries: @active_breweries, retired_breweries: @retired_breweries %>

<p>
  <%= link_to "List of beers", beers_path %>
</p>
<%= turbo_frame_tag "new_brewery", src: new_brewery_path if current_user %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/show.html.erb
<%= render @brewery %>

<div>
  <p>
    <%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), data: { turbo_method: "post" }, class: "btn btn-primary" %>
  </p>
  <p>
    <%= edit_and_destroy_buttons(@brewery) %>
  </p>
  <p>
    <%= link_to "Back to breweries", breweries_path %>
  </p>
  <%#= link_to("Edit this brewery", edit_brewery_path(@brewery)) if current_user  %>
  <%# " |" if current_user %>


  <%#= button_to("Destroy this brewery", @brewery, method: :delete, class: 'btn btn-danger') if current_user  %>
</div>